import { Product } from "../product-detail/ProductDetailPage";

export const products: Product[] = [
  {
    "id": 1,
    "name": "Oysters - Smoked",
    "imgURL": ["http://dummyimage.com/222x100.png/dddddd/000000"],
    "categoryName": "Ornamental Railings",
    "categoryId": 1,
    "status": "Còn hàng",
    "composition": "Wood",
    "country": "China",
    "brand": "Synchronoss Technologies, Inc.",
    "description":
      "Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.\n\nIn congue. Etiam justo. Etiam pretium iaculis justo.\n\nIn hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.",
    "price": 205417,
    discount: 10,
  },
  {
    "id": 2,
    "name": "Carbonated Water - Orange",
    "imgURL": ["http://dummyimage.com/146x100.png/5fa2dd/ffffff"],
    "categoryName": "Curb & Gutter",
    "categoryId": 3,
    "status": "Còn hàng",
    "composition": "Wood",
    "country": "China",
    "brand": "Dermira, Inc.",
    "description":
      "Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.\n\nEtiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.\n\nPraesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.",
    "price": 970515,
    discount: 10,
  },
  {
    "id": 3,
    "name": "Wine - Zinfandel California 2002",
    "imgURL": ["http://dummyimage.com/146x100.png/cc0000/ffffff"],
    "categoryName": "Sitework & Site Utilities",
    "categoryId": 1,
    "status": "Còn hàng",
    "composition": "Rubber",
    "country": "Philippines",
    "brand": "Splunk Inc.",
    "description":
      "Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.",
    "price": 239631,
    "discount": 10,
  },
  {
    "id": 4,
    "name": "Wine - Red, Pinot Noir, Chateau",
    "imgURL": ["http://dummyimage.com/236x100.png/ff4444/ffffff"],
    "categoryName": "Curb & Gutter",
    "categoryId": 1,
    "status": "Còn hàng",
    "composition": "Plexiglass",
    "country": "South Africa",
    "brand": "Sears Canada Inc. ",
    "description":
      "Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.\n\nIn congue. Etiam justo. Etiam pretium iaculis justo.\n\nIn hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.",
    "price": 778154,
    discount: 5,
  },
  {
    "id": 5,
    "name": "Barley - Pearl",
    "imgURL": ["http://dummyimage.com/232x100.png/ff4444/ffffff"],
    "categoryName": "Asphalt Paving",
    "categoryId": 2,
    "status": "Còn hàng",
    "composition": "Stone",
    "country": "Brazil",
    "brand": "Hecla Mining Company",
    "description":
      "Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.\n\nInteger tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.",
    "price": 106927,
    discount: 5,
  },
  {
    "id": 6,
    "name": "Wine - Ej Gallo Sierra Valley",
    "imgURL": ["http://dummyimage.com/220x100.png/dddddd/000000"],
    "categoryName": "EIFS",
    "categoryId": 3,
    "status": "Còn hàng",
    "composition": "Steel",
    "country": "Philippines",
    "brand": "Omega Healthcare Investors, Inc.",
    "description":
      "Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.",
    "price": 315777,
    discount: 5,
  },
  {
    "id": 7,
    "name": "Mushroom - Porcini, Dry",
    "imgURL": ["http://dummyimage.com/231x100.png/ff4444/ffffff"],
    "categoryName": "Drilled Shafts",
    "categoryId": 1,
    "status": "Còn hàng",
    "composition": "Steel",
    "country": "France",
    "brand": "WEC Energy Group, Inc.",
    "description":
      "Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.\n\nPellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.",
    "price": 306183,
    discount: 0,
  },
  {
    "id": 8,
    "name": "Beer - Alexander Kieths, Pale Ale",
    "imgURL": ["http://dummyimage.com/164x100.png/dddddd/000000"],
    "categoryName": "Drywall & Acoustical (MOB)",
    "categoryId": 2,
    "status": "Còn hàng",
    "composition": "Wood",
    "country": "United States",
    "brand": "Tesoro Corporation",
    "description":
      "Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.",
    "price": 623352,
    discount: 0,
  },
  {
    "id": 9,
    "name": "Wine - Carmenere Casillero Del",
    "imgURL": ["http://dummyimage.com/184x100.png/ff4444/ffffff"],
    "categoryName": "Waterproofing & Caulking",
    "categoryId": 3,
    "status": "Còn hàng",
    "composition": "Rubber",
    "country": "Philippines",
    "brand": "Pebblebrook Hotel Trust",
    "description":
      "Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.\n\nQuisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.",
    "price": 796716,
    discount: 0,
  },
  {
    "id": 10,
    "name": "Lettuce Romaine Chopped",
    "imgURL": ["http://dummyimage.com/236x100.png/cc0000/ffffff"],
    "categoryName": "Asphalt Paving",
    "categoryId": 1,
    "status": "Còn hàng",
    "composition": "Stone",
    "country": "Colombia",
    "brand": "Reinsurance Group of America, Incorporated",
    "description":
      "Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.",
    "price": 419042,
    discount: 20,
  },
  {
    "id": 11,
    "name": "Beans - Kidney, Red Dry",
    "imgURL": ["http://dummyimage.com/115x100.png/cc0000/ffffff"],
    "categoryName": "Glass & Glazing",
    "categoryId": 2,
    "status": "Còn hàng",
    "composition": "Plastic",
    "country": "China",
    "brand": "First Trust Germany AlphaDEX Fund",
    "description":
      "Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.\n\nIn hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.\n\nAliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.",
    "price": 834381,
    discount: 20,
  },
  {
    "id": 12,
    "name": "Pork - Tenderloin, Fresh",
    "imgURL": ["http://dummyimage.com/150x100.png/ff4444/ffffff"],
    "categoryName": "Framing (Steel)",
    "categoryId": 1,
    "status": "Còn hàng",
    "composition": "Aluminum",
    "country": "Japan",
    "brand": "Paycom Software, Inc.",
    "description":
      "Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.\n\nCum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.",
    "price": 189154,
    discount: 10,
  },
  {
    "id": 13,
    "name": "Crab - Imitation Flakes",
    "imgURL": ["http://dummyimage.com/130x100.png/cc0000/ffffff"],
    "categoryName": "HVAC",
    "categoryId": 2,
    "status": "Còn hàng",
    "composition": "Vinyl",
    "country": "United Kingdom",
    "brand": "Skyline Medical Inc.",
    "description":
      "Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.",
    "price": 413838,
    discount: 10,
  },
  {
    "id": 14,
    "name": "Wine - Charddonnay Errazuriz",
    "imgURL": ["http://dummyimage.com/205x100.png/cc0000/ffffff"],
    "categoryName": "Epoxy Flooring",
    "categoryId": 1,
    "status": "Còn hàng",
    "composition": "Plastic",
    "country": "Germany",
    "brand": "Bay Bancorp, Inc.",
    "description":
      "Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.",
    "price": 971021,
    discount: 10,
  },
  {
    "id": 15,
    "name": "Sausage - Breakfast",
    "imgURL": ["http://dummyimage.com/190x100.png/ff4444/ffffff"],
    "categoryName": "Hard Tile & Stone",
    "categoryId": 2,
    "status": "Còn hàng",
    "composition": "Aluminum",
    "country": "Russia",
    "brand": "Plexus Corp.",
    "description":
      "Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.\n\nPhasellus in felis. Donec semper sapien a libero. Nam dui.\n\nProin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.",
    "price": 913350,
    discount: 10,
  },
  {
    "id": 16,
    "name": "Pepper - Julienne, Frozen",
    "imgURL": ["http://dummyimage.com/160x100.png/5fa2dd/ffffff"],
    "categoryName": "Sitework & Site Utilities",
    "categoryId": 3,
    "status": "Còn hàng",
    "composition": "Brass",
    "country": "Zambia",
    "brand": "Landmark Bancorp Inc.",
    "description":
      "Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.\n\nQuisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.",
    "price": 912871,
    discount: 10,
  },
  {
    "id": 17,
    "name": "Beer - Upper Canada Lager",
    "imgURL": ["http://dummyimage.com/195x100.png/cc0000/ffffff"],
    "categoryName": "Masonry",
    "categoryId": 3,
    "status": "Còn hàng",
    "composition": "Glass",
    "country": "Azerbaijan",
    "brand": "Civeo Corporation",
    "description":
      "Sed ante. Vivamus tortor. Duis mattis egestas metus.\n\nAenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.",
    "price": 794714,
    discount: 10,
  },
  {
    "id": 18,
    "name": "Port - 74 Brights",
    "imgURL": ["http://dummyimage.com/135x100.png/cc0000/ffffff"],
    "categoryName": "Hard Tile & Stone",
    "categoryId": 3,
    "status": "Còn hàng",
    "composition": "Steel",
    "country": "Colombia",
    "brand": "Nutanix, Inc.",
    "description":
      "Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.\n\nInteger tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.",
    "price": 830624,
    discount: 10,
  },
  {
    "id": 19,
    "name": "Cup - 8oz Coffee Perforated",
    "imgURL": ["http://dummyimage.com/143x100.png/ff4444/ffffff"],
    "categoryName": "Exterior Signage",
    "categoryId": 1,
    "status": "Còn hàng",
    "composition": "Steel",
    "country": "Mongolia",
    "brand": "Delaware Enhanced Global Dividend",
    "description": "In congue. Etiam justo. Etiam pretium iaculis justo.",
    "price": 731029,
    discount: 10,
  },
  {
    "id": 20,
    "name": "Wine - Red, Mosaic Zweigelt",
    "imgURL": ["http://dummyimage.com/170x100.png/dddddd/000000"],
    "categoryName": "Plumbing & Medical Gas",
    "categoryId": 1,
    "status": "Còn hàng",
    "composition": "Vinyl",
    "country": "Thailand",
    "brand": "Mercury Systems Inc",
    "description":
      "Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.\n\nProin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.",
    "price": 590707,
    discount: 10,
  },
  {
    "id": 21,
    "name": "Bread Cranberry Foccacia",
    "imgURL": ["http://dummyimage.com/183x100.png/cc0000/ffffff"],
    "categoryName": "Electrical and Fire Alarm",
    "categoryId": 2,
    "status": "Còn hàng",
    "composition": "Stone",
    "country": "Sudan",
    "brand": "Juno Therapeutics, Inc.",
    "description":
      "Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.\n\nMorbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.",
    "price": 542084,
    discount: 10,
  },
  {
    "id": 22,
    "name": "Marjoram - Dried, Rubbed",
    "imgURL": ["http://dummyimage.com/224x100.png/dddddd/000000"],
    "categoryName": "Overhead Doors",
    "categoryId": 1,
    "status": "Còn hàng",
    "composition": "Plexiglass",
    "country": "Brazil",
    "brand": "SciClone Pharmaceuticals, Inc.",
    "description":
      "Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.",
    "price": 551444,
    discount: 10,
  },
  {
    "id": 23,
    "name": "Wine - White, Antinore Orvieto",
    "imgURL": ["http://dummyimage.com/131x100.png/5fa2dd/ffffff"],
    "categoryName": "Ornamental Railings",
    "categoryId": 3,
    "status": "Còn hàng",
    "composition": "Brass",
    "country": "Indonesia",
    "brand": "Sound Financial Bancorp, Inc.",
    "description":
      "Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.",
    "price": 679229,
    discount: 10,
  },
  {
    "id": 24,
    "name": "Chicken - Tenderloin",
    "imgURL": ["http://dummyimage.com/167x100.png/dddddd/000000"],
    "categoryName": "Elevator",
    "categoryId": 2,
    "status": "Còn hàng",
    "composition": "Vinyl",
    "country": "Albania",
    "brand": "Insight Select Income Fund",
    "description":
      "Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.\n\nSed ante. Vivamus tortor. Duis mattis egestas metus.\n\nAenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.",
    "price": 570431,
    discount: 10,
  },
  {
    "id": 25,
    "name": "Snapple Lemon Tea",
    "imgURL": ["http://dummyimage.com/176x100.png/cc0000/ffffff"],
    "categoryName": "Ornamental Railings",
    "categoryId": 2,
    "status": "Còn hàng",
    "composition": "Stone",
    "country": "San Marino",
    "brand": "Verso Corporation",
    "description":
      "Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.\n\nSed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.\n\nPellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.",
    "price": 289395,
    discount: 10,
  },
  {
    "id": 26,
    "name": "Octopus",
    "imgURL": ["http://dummyimage.com/145x100.png/5fa2dd/ffffff"],
    "categoryName": "Doors, Frames & Hardware",
    "categoryId": 3,
    "status": "Còn hàng",
    "composition": "Steel",
    "country": "Nigeria",
    "brand": "Parkway, Inc.",
    "description": "Sed ante. Vivamus tortor. Duis mattis egestas metus.",
    "price": 178249,
    discount: 10,
  },
  {
    "id": 27,
    "name": "Tomato - Peeled Italian Canned",
    "imgURL": ["http://dummyimage.com/162x100.png/cc0000/ffffff"],
    "categoryName": "Plumbing & Medical Gas",
    "categoryId": 3,
    "status": "Còn hàng",
    "composition": "Brass",
    "country": "China",
    "brand": "Blue Hills Bancorp, Inc.",
    "description":
      "Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.",
    "price": 210848,
    discount: 10,
  },
  {
    "id": 28,
    "name": "Club Soda - Schweppes, 355 Ml",
    "imgURL": ["http://dummyimage.com/166x100.png/ff4444/ffffff"],
    "categoryName": "Doors, Frames & Hardware",
    "categoryId": 3,
    "status": "Còn hàng",
    "composition": "Glass",
    "country": "Brazil",
    "brand": "Pioneer Energy Services Corp.",
    "description":
      "Fusce consequat. Nulla nisl. Nunc nisl.\n\nDuis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.",
    "price": 199209,
    discount: 10,
  },
  {
    "id": 29,
    "name": "Beef - Baby, Liver",
    "imgURL": ["http://dummyimage.com/180x100.png/dddddd/000000"],
    "categoryName": "Drywall & Acoustical (FED)",
    "categoryId": 3,
    "status": "Còn hàng",
    "composition": "Plexiglass",
    "country": "Cyprus",
    "brand": "Diffusion Pharmaceuticals Inc.",
    "description":
      "In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.\n\nNulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.",
    "price": 712149,
    discount: 10,
  },
  {
    "id": 30,
    "name": "Pate - Peppercorn",
    "imgURL": ["http://dummyimage.com/181x100.png/5fa2dd/ffffff"],
    "categoryName": "Electrical and Fire Alarm",
    "categoryId": 2,
    "status": "Còn hàng",
    "composition": "Glass",
    "country": "Indonesia",
    "brand": "Columbia Sportswear Company",
    "description":
      "Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.",
    "price": 359818,
    discount: 10,
  },
  {
    "id": 31,
    "name": "Veal - Insides Provini",
    "imgURL": ["http://dummyimage.com/120x100.png/cc0000/ffffff"],
    "categoryName": "Casework",
    "categoryId": 3,
    "status": "Còn hàng",
    "composition": "Glass",
    "country": "France",
    "brand": "Shoe Carnival, Inc.",
    "description":
      "In congue. Etiam justo. Etiam pretium iaculis justo.\n\nIn hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.",
    "price": 222747,
    discount: 10,
  },
  {
    "id": 32,
    "name": "Kellogs All Bran Bars",
    "imgURL": ["http://dummyimage.com/233x100.png/dddddd/000000"],
    "categoryName": "EIFS",
    "categoryId": 2,
    "status": "Còn hàng",
    "composition": "Wood",
    "country": "Philippines",
    "brand": "Analog Devices, Inc.",
    "description":
      "Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.",
    "price": 627138,
    discount: 10,
  },
  {
    "id": 33,
    "name": "Table Cloth 72x144 White",
    "imgURL": ["http://dummyimage.com/207x100.png/dddddd/000000"],
    "categoryName": "Marlite Panels (FED)",
    "categoryId": 1,
    "status": "Còn hàng",
    "composition": "Wood",
    "country": "France",
    "brand": "Colony NorthStar, Inc.",
    "description":
      "Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.\n\nIn sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.\n\nSuspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.",
    "price": 276987,
    discount: 10,
  },
  {
    "id": 34,
    "name": "Wine - Tio Pepe Sherry Fino",
    "imgURL": ["http://dummyimage.com/118x100.png/dddddd/000000"],
    "categoryName": "Construction Clean and Final Clean",
    "categoryId": 1,
    "status": "Còn hàng",
    "composition": "Steel",
    "country": "Peru",
    "brand": "Ohr Pharmaceuticals, Inc.",
    "description":
      "Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.",
    "price": 845430,
    discount: 10,
  },
  {
    "id": 35,
    "name": "Flour - Fast / Rapid",
    "imgURL": ["http://dummyimage.com/184x100.png/cc0000/ffffff"],
    "categoryName": "Granite Surfaces",
    "categoryId": 2,
    "status": "Còn hàng",
    "composition": "Stone",
    "country": "Portugal",
    "brand": "ENDRA Life Sciences Inc.",
    "description":
      "Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.\n\nPraesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.",
    "price": 239950,
    discount: 10,
  },
  {
    "id": 36,
    "name": "Cheese - Grie Des Champ",
    "imgURL": ["http://dummyimage.com/132x100.png/5fa2dd/ffffff"],
    "categoryName": "Asphalt Paving",
    "categoryId": 1,
    "status": "Còn hàng",
    "composition": "Stone",
    "country": "China",
    "brand": "Scholastic Corporation",
    "description":
      "Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.\n\nFusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.",
    "price": 800834,
    discount: 10,
  },
  {
    "id": 37,
    "name": "Bread - Roll, Soft White Round",
    "imgURL": ["http://dummyimage.com/105x100.png/ff4444/ffffff"],
    "categoryName": "Fire Sprinkler System",
    "categoryId": 3,
    "status": "Còn hàng",
    "composition": "Aluminum",
    "country": "Finland",
    "brand": "AGNC Investment Corp.",
    "description":
      "Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.",
    "price": 624633,
    discount: 10,
  },
  {
    "id": 38,
    "name": "Tomatoes - Cherry, Yellow",
    "imgURL": ["http://dummyimage.com/210x100.png/ff4444/ffffff"],
    "categoryName": "Marlite Panels (FED)",
    "categoryId": 1,
    "status": "Còn hàng",
    "composition": "Glass",
    "country": "Belarus",
    "brand": "Blackrock MuniYield Fund, Inc.",
    "description":
      "Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.\n\nInteger ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.\n\nNam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.",
    "price": 207505,
    discount: 10,
  },
  {
    "id": 39,
    "name": "Coffee Beans - Chocolate",
    "imgURL": ["http://dummyimage.com/200x100.png/cc0000/ffffff"],
    "categoryName": "Masonry & Precast",
    "categoryId": 1,
    "status": "Còn hàng",
    "composition": "Glass",
    "country": "Denmark",
    "brand": "PAVmed Inc.",
    "description":
      "Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.",
    "price": 337926,
    discount: 10,
  },
  {
    "id": 40,
    "name": "Sherbet - Raspberry",
    "imgURL": ["http://dummyimage.com/135x100.png/dddddd/000000"],
    "categoryName": "Site Furnishings",
    "categoryId": 1,
    "status": "Còn hàng",
    "composition": "Aluminum",
    "country": "Russia",
    "brand": "Condor Hospitality Trust, Inc.",
    "description":
      "Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.\n\nNam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.\n\nCurabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.",
    "price": 519150,
    discount: 10,
  },
  {
    "id": 41,
    "name": "Nut - Almond, Blanched, Ground",
    "imgURL": ["http://dummyimage.com/149x100.png/dddddd/000000"],
    "categoryName": "Drywall & Acoustical (FED)",
    "categoryId": 1,
    "status": "Còn hàng",
    "composition": "Rubber",
    "country": "China",
    "brand": "Chesapeake Energy Corporation",
    "description":
      "Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.\n\nCurabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.",
    "price": 619460,
    discount: 10,
  },
  {
    "id": 42,
    "name": "Oil - Macadamia",
    "imgURL": ["http://dummyimage.com/193x100.png/cc0000/ffffff"],
    "categoryName": "Drywall & Acoustical (MOB)",
    "categoryId": 1,
    "status": "Còn hàng",
    "composition": "Glass",
    "country": "Ireland",
    "brand": "TCF Financial Corporation",
    "description":
      "Phasellus in felis. Donec semper sapien a libero. Nam dui.\n\nProin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.",
    "price": 476599,
    discount: 10,
  },
  {
    "id": 43,
    "name": "Flower - Commercial Spider",
    "imgURL": ["http://dummyimage.com/102x100.png/5fa2dd/ffffff"],
    "categoryName": "Waterproofing & Caulking",
    "categoryId": 2,
    "status": "Còn hàng",
    "composition": "Plexiglass",
    "country": "Honduras",
    "brand": "Dorian LPG Ltd.",
    "description":
      "Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.\n\nEtiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.",
    "price": 405122,
    discount: 10,
  },
  {
    "id": 44,
    "name": "Pork Ham Prager",
    "imgURL": ["http://dummyimage.com/230x100.png/cc0000/ffffff"],
    "categoryName": "EIFS",
    "categoryId": 2,
    "status": "Còn hàng",
    "composition": "Wood",
    "country": "Guatemala",
    "brand": "Alibaba Group Holding Limited",
    "description":
      "Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.\n\nInteger tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.\n\nPraesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.",
    "price": 808873,
    discount: 10,
  },
  {
    "id": 45,
    "name": "Lettuce - Boston Bib - Organic",
    "imgURL": ["http://dummyimage.com/205x100.png/cc0000/ffffff"],
    "categoryName": "Waterproofing & Caulking",
    "categoryId": 1,
    "status": "Còn hàng",
    "composition": "Glass",
    "country": "Jamaica",
    "brand": "Steven Madden, Ltd.",
    "description":
      "Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.\n\nSed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.\n\nPellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.",
    "price": 382422,
    discount: 10,
  },
  {
    "id": 46,
    "name": "Wine - Riesling Dr. Pauly",
    "imgURL": ["http://dummyimage.com/166x100.png/dddddd/000000"],
    "categoryName": "Retaining Wall and Brick Pavers",
    "categoryId": 3,
    "status": "Còn hàng",
    "composition": "Steel",
    "country": "China",
    "brand": "Gabelli Utility Trust (The)",
    "description":
      "In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.",
    "price": 866407,
    discount: 10,
  },
  {
    "id": 47,
    "name": "Hersey Shakes",
    "imgURL": ["http://dummyimage.com/180x100.png/5fa2dd/ffffff"],
    "categoryName": "Plumbing & Medical Gas",
    "categoryId": 2,
    "status": "Còn hàng",
    "composition": "Plexiglass",
    "country": "Indonesia",
    "brand": "Ebix, Inc.",
    "description":
      "Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.\n\nSed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.",
    "price": 629385,
    discount: 10,
  },
  {
    "id": 48,
    "name": "Long Island Ice Tea",
    "imgURL": ["http://dummyimage.com/111x100.png/dddddd/000000"],
    "categoryName": "Masonry",
    "categoryId": 1,
    "status": "Còn hàng",
    "composition": "Plastic",
    "country": "Philippines",
    "brand": "The Health and Fitness ETF",
    "description":
      "Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.\n\nPhasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.\n\nProin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.",
    "price": 299352,
    discount: 10,
  },
  {
    "id": 49,
    "name": "Wine - Red, Cooking",
    "imgURL": ["http://dummyimage.com/163x100.png/dddddd/000000"],
    "categoryName": "Waterproofing & Caulking",
    "categoryId": 3,
    "status": "Còn hàng",
    "composition": "Plastic",
    "country": "China",
    "brand": "Zafgen, Inc.",
    "description":
      "Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.\n\nIn sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.",
    "price": 329759,
    discount: 10,
  },
  {
    "id": 50,
    "name": "Melon - Cantaloupe",
    "imgURL": ["http://dummyimage.com/224x100.png/5fa2dd/ffffff"],
    "categoryName": "Plumbing & Medical Gas",
    "categoryId": 2,
    "status": "Còn hàng",
    "composition": "Vinyl",
    "country": "Philippines",
    "brand": "MBIA, Inc.",
    "description":
      "Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.\n\nIn congue. Etiam justo. Etiam pretium iaculis justo.",
    "price": 741132,
    discount: 10,
  },
];
